### ISSUE TITLE
Arquitetura de micro-serviços

### ISSUE THREAD

**Issue by keyboard99** [devfridays/talks#2]
Título: Arquitetura de micro-serviços
Descrição: 

- micro-serviços vs monolíticos
- comparativo de arquitetura micro-serviço vs monolítica
- estrutura de projeto em micro-serviços
- comunicação entre micro-serviços
- containers e deploy

**Comment by jackmiras** [comment]
[Arquitetura de micro-serviços - startup.pdf](https://github.com/devfridays/talks/files/1102204/Arquitetura.de.micro-servicos.-.startup.pdf)
